### ISSUE TITLE
lookup throws error with default config when no AAAA records

### ISSUE THREAD

**Issue by iiroj** [LCMApps/dns-lookup-cache#56]
It seems that using the default config, `lookup` will throw an error when looking up addresses for a host that has only IPv4 records.

**default config**
```js
lookup('ipv4-only-hostname', (error, results) => {
    if (error) {
        console.error(error)
    }
    console.log(results)
})
// Error: Empty "AAAA" records list for ipv4-only-hostname
// undefined
```

**family: 4**
```js
lookup('ipv4-only-hostname', { family: 4 }, (error, results) => {
    if (error) {
        console.error(error)
    }
    console.log(results)
})
// 127.0.0.1
```

**family: 6**
```js
lookup('ipv4-only-hostname', { family: 6 }, (error, results) => {
    if (error) {
        console.error(error)
    }
    console.log(results)
})
// Error: Empty "AAAA" records list for ipv4-only-hostname
// undefined
```

**all: true**
```js
lookup('ipv4-only-hostname', { all: true }, (error, results) => {
    if (error) {
        console.error(error)
    }
    console.log(results)
})
// [
//   { address: '127.0.0.1', family: 4 }
// ]
```
## Expected behaviour:

I would like the default settings to simply work, by ignoring missing IPv6 addresses and returning the IPv4.

For the record, I'm using the named `lookup` export and passing it directly to a `https.Agent`:

```js
import { lookup } from 'dns-lookup-cache'
const agent = https.Agent({ lookup })
```

Thoughts?

**Comment by WoZ** [comment]
Hello! Thank you for the issue. May you provide an output of 'dig' command for the domain you are testing or the name of domain to check?

I suppose that the issue in smth other. Here is an example. google.com has A and AAAA records, github.com has only A record. Check dig output:

```
$ dig google.com AAAA

; <<>> DiG 9.10.6 <<>> google.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44389
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1

;; QUESTION SECTION:
;google.com.			IN	AAAA

;; ANSWER SECTION:
google.com.		212	IN	AAAA	2a00:1450:4003:80a::200e

;; AUTHORITY SECTION:
google.com.		345191	IN	NS	ns2.google.com.
google.com.		345191	IN	NS	ns4.google.com.
google.com.		345191	IN	NS	ns3.google.com.
google.com.		345191	IN	NS	ns1.google.com.

;; ADDITIONAL SECTION:
ns4.google.com.		21526	IN	A	216.239.38.10

;; Query time: 60 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Aug 30 15:20:03 EEST 2019
;; MSG SIZE  rcvd: 144
```

```
$ dig github.com AAAA

; <<>> DiG 9.10.6 <<>> github.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16127
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 8, ADDITIONAL: 1

;; QUESTION SECTION:
;github.com.			IN	AAAA

;; AUTHORITY SECTION:
github.com.		50	IN	NS	ns2.p16.dynect.net.
github.com.		50	IN	NS	ns3.p16.dynect.net.
github.com.		50	IN	NS	ns4.p16.dynect.net.
github.com.		50	IN	NS	ns-1283.awsdns-32.org.
github.com.		50	IN	NS	ns-1707.awsdns-21.co.uk.
github.com.		50	IN	NS	ns-421.awsdns-52.com.
github.com.		50	IN	NS	ns-520.awsdns-01.net.
github.com.		50	IN	NS	ns1.p16.dynect.net.

;; ADDITIONAL SECTION:
ns-1707.awsdns-21.co.uk. 20978	IN	A	205.251.198.171

;; Query time: 59 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Aug 30 15:20:20 EEST 2019
;; MSG SIZE  rcvd: 264
```

Code to check.
```
const {lookup} = require('dns-lookup-cache');

function printSingleResult(testName) {
    return (error, address, family) => {
        if (error) {
            console.log(testName, error);
            return;
        }

        console.log(`${testName}: IPv${family}: ${address}`);
        console.log('-------');
    };
}

lookup('google.com', {}, printSingleResult('google.com, default'));
lookup('google.com', {family: 4}, printSingleResult('google.com, family: 4'));
lookup('google.com', {family: 6}, printSingleResult('google.com, family: 6'));

lookup('github.com', {}, printSingleResult('github.com, default'));
lookup('github.com', {family: 4}, printSingleResult('github.com, family: 4'));
lookup('github.com', {family: 6}, printSingleResult('github.com, family: 6'));
```

Output is
```
$ node index.js
google.com, family: 4: IPv4: 172.217.168.174
-------
github.com, family: 4: IPv4: 140.82.118.4
-------
google.com, family: 6: IPv6: 2a00:1450:4003:80a::200e
-------
google.com, default: IPv4: 172.217.168.174
-------
github.com, family: 6 { Error: queryAaaa ENOTFOUND github.com
    at Lookup._makeNotFoundError (/Users/woz/projects/dnstest/node_modules/dns-lookup-cache/src/Lookup.js:261:30)
    at _innerResolve.then.catch.error (/Users/woz/projects/dnstest/node_modules/dns-lookup-cache/src/Lookup.js:165:32)
  hostname: 'github.com',
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'queryAaaa' }
github.com, default: IPv4: 140.82.118.4
-------
```


So, default config with no AAAA records on github.com works well.
Did you reconfigure resolv.conf?

**Comment by iiroj** [comment]
Hello,

thanks for the response. The test you provided is working correctly, so it seems the issue is in the specific domain I am querying.

The only difference I can see is that for the domain, `dig ipv4-only-hostname AAAA` returns only a `CNAME` record, when `dig ipv4-only-hostname A` returns both `CNAME` and multiple `A` records.

So maybe it's regarding resolution of `CNAME` records?

**Comment by WoZ** [comment]
It's because of your host `ipv4-only-hostname` has `CNAME` that has only `A` record. If CNAME of `ipv4-only-hostname` has `AAAA` record you get it.

Check the [RFC-1034](https://tools.ietf.org/html/rfc1034), section 3.6.2.

```
If a CNAME RR is present at a node, no other data should be
present; this ensures that the data for a canonical name and its aliases
cannot be different.  This rule also insures that a cached CNAME can be
used without checking with an authoritative server for other RR types.

CNAME RRs cause special action in DNS software.  When a name server
fails to find a desired RR in the resource set associated with the
domain name, it checks to see if the resource set consists of a CNAME
record with a matching class.
```
